// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5112.GearBoxTest;

import org.usfirst.frc5112.GearBoxTest.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	public Joystick joystick;
	public JoystickButton forwards;
	public JoystickButton backwards;
	public JoystickButton stop;
	public JoystickButton testGears;
	public JoystickButton invertMotors;
	public JoystickButton defaultMotorDirection;
	
	
	public OI() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

		joystick = new Joystick(0);
		forwards = new JoystickButton(joystick, 1);
		backwards = new JoystickButton(joystick, 3);
		stop = new JoystickButton(joystick, 4);
		testGears = new JoystickButton(joystick, 5);
		defaultMotorDirection = new JoystickButton(joystick, 6);
		invertMotors = new JoystickButton(joystick, 7);
		
		
		// SmartDashboard Buttons
		SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
		SmartDashboard.putData("Forwards", new Forwards());
		SmartDashboard.putData("Backwards", new Backwards());
		SmartDashboard.putData("Invert Motors", new invertMotors());
		SmartDashboard.putData("Default Motor Direction", new defaultMotorDirection());
		
		forwards.whileHeld(new Forwards());
		backwards.whileHeld(new Backwards());
		stop.whenPressed(new Stop());
		testGears.whenPressed(new ForwardsBakcwardsEtc());
		invertMotors.whenPressed(new invertMotors());
		defaultMotorDirection.whenPressed(new defaultMotorDirection());
		
		
		
		
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		
	}

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
	public Joystick getjoystick() {
		return joystick;
	}

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
